### ISSUE TITLE
Clarify references to parts of the source code

### ISSUE THREAD

**Issue by LukasDrude** [sas91/jhu-neural-wpe#1]
Dear Aswin,

I would kindly like to ask to clarify in the readme, where at least parts of the code come from. For example this line in your code [1] seems to be very similar to our code [2].

I think it is nice that you rightfully cite Keisuke's work. However, I would appreciate if you could also link back to Nara-WPE [3] or even include the reference to the corresponding paper for the implementation:

```
@InProceedings{Drude2018NaraWPE,
  Title     = {{NARA-WPE: A Python package for weighted prediction error dereverberation in Numpy and Tensorflow for online and offline processing}},
  Author    = {Drude, Lukas and Heymann, Jahn and Boeddeker, Christoph and Haeb-Umbach, Reinhold},
  Booktitle = {13. ITG Fachtagung Sprachkommunikation (ITG 2018)},
  Year      = {2018},
  Month     = {Oct},
}
```

[1] https://github.com/sas91/jhu-neural-wpe/blob/master/src/wpe.py#L51
[2] https://github.com/fgnt/nara_wpe/blob/master/nara_wpe/wpe.py#L227
[3] https://github.com/fgnt/nara_wpe

**Comment by sw005320** [comment]
@LukasDrude, thanks for your note. 
@sas91, please include them.

**Comment by sas91** [comment]
@LukasDrude Thanks for your note. Yes, the part you mentioned is based on your NARA-WPE, that is why I have a given a reference to your repo above in this line https://github.com/sas91/jhu-neural-wpe/blob/master/src/wpe.py#L5. I see it is better to include a reference also in the README, I will add it now.
